# Generated by Django 4.2.1 on 2023-06-04 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_date', models.CharField(max_length=10)),
                ('news_title', models.CharField(max_length=100)),
                ('news_context', models.CharField(max_length=200)),
                ('news_source', models.CharField(max_length=30)),
            ],
        ),
    ]
