# Generated by Django 4.2.1 on 2023-06-20 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatEpl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('team', models.CharField(max_length=50)),
                ('matches', models.IntegerField()),
                ('win', models.IntegerField()),
                ('draw', models.IntegerField()),
                ('loss', models.IntegerField()),
                ('scored', models.IntegerField()),
                ('conceded', models.IntegerField()),
                ('points', models.IntegerField()),
                ('season', models.CharField(max_length=15)),
            ],
        ),
    ]
