# Generated by Django 4.2.1 on 2023-06-08 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_context',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_source',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_title',
            field=models.CharField(max_length=200),
        ),
    ]
