# Generated by Django 4.2.1 on 2023-06-21 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_statepl'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalscorersEPL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('player_name', models.CharField(max_length=50)),
                ('team_name', models.CharField(max_length=50)),
                ('goals', models.IntegerField()),
            ],
        ),
    ]
