# Generated by Django 4.2.1 on 2023-06-09 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_alter_news_news_context_alter_news_news_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="news",
            old_name="news_date",
            new_name="date",
        ),
        migrations.RenameField(
            model_name="news",
            old_name="news_title",
            new_name="title",
        ),
        migrations.RemoveField(
            model_name="news",
            name="news_context",
        ),
        migrations.RemoveField(
            model_name="news",
            name="news_source",
        ),
        migrations.AddField(
            model_name="news",
            name="source",
            field=models.URLField(default=""),
            preserve_default=False,
        ),
    ]
