# Generated by Django 4.2.1 on 2023-06-12 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_rename_news_date_news_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="date",
            field=models.DateTimeField(),
        ),
    ]
