# Generated by Django 4.2.1 on 2023-06-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0004_alter_news_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="team",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="news",
            name="title",
            field=models.TextField(),
        ),
    ]
