# Generated by Django 4.2.1 on 2023-06-26 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fwa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistentsEPL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('player_name', models.CharField(max_length=50)),
                ('team_name', models.CharField(max_length=50)),
                ('assists', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CalendarMatches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_match', models.DateTimeField()),
                ('tournament', models.CharField(max_length=50)),
                ('opposite_team', models.CharField(max_length=50)),
                ('place_match', models.CharField(max_length=10)),
                ('match_score', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='GoalscorersEPL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('player_name', models.CharField(max_length=50)),
                ('team_name', models.CharField(max_length=50)),
                ('goals', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StatEpl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('team', models.CharField(max_length=50)),
                ('matches', models.IntegerField()),
                ('win', models.IntegerField()),
                ('draw', models.IntegerField()),
                ('loss', models.IntegerField()),
                ('scored', models.IntegerField()),
                ('conceded', models.IntegerField()),
                ('points', models.IntegerField()),
                ('season', models.CharField(max_length=15)),
            ],
        ),
    ]
