# Generated by Django 4.2.1 on 2023-06-29 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fwa', '0003_assistentsepl_season_calendarmatches_season_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assistentsepl',
            old_name='player_name',
            new_name='player',
        ),
        migrations.RenameField(
            model_name='goalscorersepl',
            old_name='player_name',
            new_name='player',
        ),
        migrations.RemoveField(
            model_name='assistentsepl',
            name='team_name',
        ),
        migrations.RemoveField(
            model_name='goalscorersepl',
            name='team_name',
        ),
        migrations.AddField(
            model_name='assistentsepl',
            name='team',
            field=models.ForeignKey(default=25, on_delete=django.db.models.deletion.CASCADE, to='fwa.teams'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goalscorersepl',
            name='team',
            field=models.ForeignKey(default=25, on_delete=django.db.models.deletion.CASCADE, to='fwa.teams'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='statepl',
            name='team',
        ),
        migrations.AddField(
            model_name='statepl',
            name='team',
            field=models.ForeignKey(default=25, on_delete=django.db.models.deletion.CASCADE, to='fwa.teams'),
            preserve_default=False,
        ),
    ]
