# Generated by Django 4.2.1 on 2023-07-04 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fwa', '0004_rename_player_name_assistentsepl_player_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='logo',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teams',
            name='tag',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teams',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
