# Generated by Django 4.2.1 on 2023-07-04 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fwa', '0005_teams_logo_teams_tag_teams_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='logo',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='teams',
            name='tag',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='teams',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
